services:
  postgres:
    image: postgres:16
    container_name: hiretrack-postgres
    environment:
      POSTGRES_DB: hiretrack
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  hiretrack:
    image: ferdin1/hiretrack:latest
    container_name: hiretrack-app
    ports:
      - "8080:8080"
    environment:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hiretrack
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:7
    container_name: ratelimiter-redis
    ports:
      - "6379:6379"

  gateway-1:
    build: .
    container_name: gateway-1
    ports:
      - "9001:9000"
    environment:
      SPRING_DATA_REDIS_HOST: redis
      GATEWAY_BACKEND_URL: http://hiretrack:8080
      GATEWAY_JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    depends_on:
      - redis
      - hiretrack

  gateway-2:
    build: .
    container_name: gateway-2
    ports:
      - "9002:9000"
    environment:
      SPRING_DATA_REDIS_HOST: redis
      GATEWAY_BACKEND_URL: http://hiretrack:8080
      GATEWAY_JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    depends_on:
      - redis
      - hiretrack

  gateway-3:
    build: .
    container_name: gateway-3
    ports:
      - "9003:9000"
    environment:
      SPRING_DATA_REDIS_HOST: redis
      GATEWAY_BACKEND_URL: http://hiretrack:8080
      GATEWAY_JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    depends_on:
      - redis
      - hiretrack

  demo:
    build:
      context: .
      dockerfile: Dockerfile.demo
    container_name: gateway-demo
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - gateway-1
      - gateway-2
      - gateway-3
    profiles:
      - demo